#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a #v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: adnanhemani821/polaris
          flavor: |
            latest=false

      - name: Docker Image build
        run: |
          ./gradlew \
            :polaris-quarkus-server:assemble \
            :polaris-quarkus-server:quarkusAppPartsBuild --rerun \
            :polaris-quarkus-admin:assemble \
            :polaris-quarkus-admin:quarkusAppPartsBuild --rerun \
            -Dquarkus.container-image.build=true \
            -PeclipseLinkDeps=org.postgresql:postgresql:42.7.4

      - name: List all Docker images
        run: docker images

      - name: Push Docker image to Docker Hub
        run: |
          IFS=$'\n' read -rd '' TAGS <<< "$(echo -e '${{ steps.meta.outputs.tags }}')"
          for TAG in ${TAGS[@]}; do
            # Replace everything before the first "/" or ":" with "abcd"
            LOCAL_TAG=$(echo "$TAG" | sed -E 's|^[^:/]+|apache|')
            echo "$LOCAL_TAG"
            docker image tag $LOCAL_TAG $TAG
            docker push $TAG
          done
